import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { BookOpen, CalendarDays, ChevronRight, Download, FileCheck2, FileText, FolderOpen, Loader2, Plus, Search, Shield, Wallet, X } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const labels: Record<string, string> = { governance: "Governança", rules: "Regulamento", finance: "Financeiro", meeting: "Assembleias", other: "Outros" };
const categoryIcons: Record<string, typeof FileText> = { governance: Shield, rules: BookOpen, finance: Wallet, meeting: CalendarDays, other: FileText };

function formatDate(value: Date | string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)); }

export default function Documents() {
  const { isAuthenticated } = useAuth();
  const { data: overview } = trpc.condo.dashboard.overview.useQuery(undefined, { enabled: isAuthenticated });
  const { data } = trpc.condo.documents.list.useQuery(undefined, { enabled: isAuthenticated && !!overview?.scope });
  const utils = trpc.useUtils();
  const create = trpc.condo.documents.create.useMutation({ onSuccess: async () => { await utils.condo.documents.list.invalidate(); await utils.condo.dashboard.overview.invalidate(); setShowForm(false); setForm({ title: "", description: "", category: "rules", fileUrl: "", fileKey: "" }); } });
  const [showForm, setShowForm] = useState(false);
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [form, setForm] = useState({ title: "", description: "", category: "rules" as "governance" | "rules" | "finance" | "meeting" | "other", fileUrl: "", fileKey: "" });
  const documents = data ?? [];
  const isStaff = overview?.scope?.isStaff ?? false;
  const filtered = documents.filter(document => (filter === "all" || document.category === filter) && document.title.toLowerCase().includes(search.toLowerCase()));

  return (
    <div className="mx-auto max-w-[1100px] space-y-7">
      <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-primary"><FolderOpen className="h-3.5 w-3.5" /> Biblioteca do condomínio</div><h1 className="text-2xl font-extrabold tracking-[-0.04em] sm:text-3xl">Documentos</h1><p className="mt-1 text-sm text-muted-foreground">Regulamentos, atas e informações importantes, sempre acessíveis.</p></div>{isStaff && <Button onClick={() => setShowForm(value => !value)} className="rounded-xl">{showForm ? <X className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{showForm ? "Fechar" : "Adicionar documento"}</Button>}</header>

      {showForm && <form onSubmit={event => { event.preventDefault(); create.mutate({ ...form, fileKey: form.fileKey || form.title.toLowerCase().replace(/\s+/g, "-") }); }} className="rounded-2xl border border-primary/20 bg-primary/[0.04] p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><FileCheck2 className="h-4 w-4" /></div><div><h2 className="font-extrabold">Adicionar documento</h2><p className="text-xs text-muted-foreground">No MVP, cadastre um link seguro para o arquivo. Upload direto entra na próxima etapa.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-bold">Título</span><input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Ex.: Ata da assembleia — setembro/2026" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" /></label><label><span className="mb-1.5 block text-xs font-bold">Categoria</span><select value={form.category} onChange={event => setForm({ ...form, category: event.target.value as typeof form.category })} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary"><option value="rules">Regulamento</option><option value="governance">Governança</option><option value="finance">Financeiro</option><option value="meeting">Assembleias</option><option value="other">Outros</option></select></label><label><span className="mb-1.5 block text-xs font-bold">Link do arquivo</span><input required type="url" value={form.fileUrl} onChange={event => setForm({ ...form, fileUrl: event.target.value })} placeholder="https://..." className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" /></label><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-bold">Descrição <span className="font-normal text-muted-foreground">(opcional)</span></span><input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Para facilitar a busca e o entendimento" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" /></label></div><div className="mt-4 flex justify-end"><Button type="submit" disabled={create.isPending} className="rounded-xl">{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar documento</Button></div></form>}

      <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-border/80 bg-card p-4"><p className="text-2xl font-extrabold">{documents.length}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">documentos ativos</p></div><div className="rounded-2xl border border-border/80 bg-card p-4"><p className="text-2xl font-extrabold">{new Set(documents.map(document => document.category)).size}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">categorias com conteúdo</p></div></div>

      <div className="flex flex-col gap-3 border-b border-border pb-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{[["all", "Todos"], ["governance", "Governança"], ["rules", "Regulamentos"], ["finance", "Financeiro"], ["meeting", "Assembleias"]].map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3.5 py-2 text-xs font-bold transition ${filter === value ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:bg-accent hover:text-accent-foreground"}`}>{label}</button>)}</div><label className="flex h-10 items-center gap-2 rounded-xl border border-border bg-background px-3 text-muted-foreground lg:w-64"><Search className="h-4 w-4" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar documento" className="min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-muted-foreground/70" /></label></div>

      <div className="grid gap-4 sm:grid-cols-2">{filtered.map(document => { const Icon = categoryIcons[document.category] ?? FileText; return <a key={document.id} href={document.fileUrl} target={document.fileUrl === "#" ? undefined : "_blank"} rel="noreferrer" className="group rounded-2xl border border-border/80 bg-card p-5 transition hover:-translate-y-0.5 hover:border-primary/25 hover:shadow-[0_14px_30px_-24px_rgba(20,50,70,0.5)]"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#fff3d9] text-[#b77a20]"><Icon className="h-[18px] w-[18px]" /></div><div className="flex items-center gap-1 text-[10px] font-bold text-muted-foreground opacity-0 transition group-hover:opacity-100"><Download className="h-3.5 w-3.5" /> Abrir</div></div><h2 className="mt-5 text-sm font-extrabold tracking-[-0.02em]">{document.title}</h2><p className="mt-1.5 line-clamp-2 min-h-[36px] text-xs leading-5 text-muted-foreground">{document.description || "Documento disponível para consulta dos moradores."}</p><div className="mt-5 flex items-center justify-between border-t border-border/60 pt-3"><span className="text-[10px] font-bold uppercase tracking-[0.1em] text-primary">{labels[document.category]}</span><span className="text-[10px] font-medium text-muted-foreground">{formatDate(document.createdAt)}</span></div></a> })}</div>
      {filtered.length === 0 && <div className="rounded-2xl bg-muted/60 p-10 text-center text-sm text-muted-foreground">Nenhum documento encontrado.</div>}
      {!isAuthenticated && <div className="rounded-2xl border border-dashed border-primary/25 bg-primary/[0.04] p-5 text-center"><p className="text-sm font-bold">Entre para acessar a biblioteca completa do seu condomínio.</p><Button variant="outline" onClick={() => startLogin()} className="mt-3 rounded-xl bg-background">Entrar na plataforma</Button></div>}
      <Link href="/" className="inline-flex items-center gap-1 text-xs font-bold text-primary">← Voltar para a visão geral <ChevronRight className="h-3.5 w-3.5 rotate-180" /></Link>
    </div>
  );
}
