import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Check, Clipboard, Copy, Link2, Loader2, Mail, Plus, ShieldCheck, UserPlus, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const roles: Record<string, string> = { resident: "Morador", staff: "Funcionário", manager: "Gestor" };
const statuses: Record<string, string> = { pending: "Pendente", accepted: "Aceito", expired: "Expirado", revoked: "Revogado" };

function formatDate(value: Date | string) {
  return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));
}

export default function Invites() {
  const { isAuthenticated } = useAuth();
  const { data: overview } = trpc.condo.dashboard.overview.useQuery(undefined, { enabled: isAuthenticated });
  const isStaff = overview?.scope.isStaff ?? false;
  const { data: invites, isLoading } = trpc.invitations.list.useQuery(undefined, { enabled: isAuthenticated && isStaff });
  const utils = trpc.useUtils();
  const create = trpc.invitations.create.useMutation({ onSuccess: async result => { await utils.invitations.list.invalidate(); setCreated(result); setShowForm(false); } });
  const revoke = trpc.invitations.revoke.useMutation({ onSuccess: () => utils.invitations.list.invalidate() });
  const [showForm, setShowForm] = useState(false);
  const [copied, setCopied] = useState(false);
  const [created, setCreated] = useState<{ token: string; expiresAt: Date; email: string | null; condominiumName: string } | null>(null);
  const [form, setForm] = useState({ email: "", role: "resident" as "resident" | "staff" | "manager", unit: "", block: "", expiresInDays: 7 });

  const inviteUrl = created ? `${window.location.origin}/invite/${created.token}` : "";
  const emailSubject = created ? `Convite para acessar o ${created.condominiumName}` : "Convite para acessar o condomínio";
  const emailBody = created ? `Olá!\n\nVocê foi convidado para acessar o ${created.condominiumName} no CondoHub.\n\nAcesse seu convite por este link: ${inviteUrl}\n\nO link é válido até ${formatDate(created.expiresAt)}.` : "";
  const copyLink = async () => { await navigator.clipboard?.writeText(inviteUrl); setCopied(true); setTimeout(() => setCopied(false), 1800); };

  if (!isAuthenticated) {
    return <div className="mx-auto max-w-xl rounded-2xl border border-dashed border-primary/25 bg-primary/[0.04] p-8 text-center"><UserPlus className="mx-auto h-8 w-8 text-primary" /><h1 className="mt-4 text-xl font-extrabold">Convites da equipe</h1><p className="mt-2 text-sm text-muted-foreground">Entre para gerar e acompanhar convites do seu condomínio.</p><Button onClick={() => startLogin()} className="mt-5 rounded-xl">Entrar na plataforma</Button></div>;
  }

  if (!isStaff) {
    return <div className="mx-auto max-w-xl rounded-2xl border border-border/80 bg-card p-8 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-muted-foreground" /><h1 className="mt-4 text-xl font-extrabold">Acesso restrito</h1><p className="mt-2 text-sm text-muted-foreground">A geração de convites está disponível para gestores e funcionários autorizados.</p><Link href="/" className="mt-5 inline-flex text-sm font-bold text-primary">Voltar para a visão geral</Link></div>;
  }

  return (
    <div className="mx-auto max-w-[1100px] space-y-7">
      <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-primary"><UsersRound className="h-3.5 w-3.5" /> Gestão de acesso</div><h1 className="text-2xl font-extrabold tracking-[-0.04em] sm:text-3xl">Convites</h1><p className="mt-1 text-sm text-muted-foreground">Vincule novos moradores e colaboradores ao condomínio em poucos passos.</p></div><Button onClick={() => { setShowForm(value => !value); setCreated(null); }} className="rounded-xl">{showForm ? <X className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{showForm ? "Fechar" : "Novo convite"}</Button></header>

      <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-border/80 bg-card p-5"><p className="text-2xl font-extrabold">{invites?.filter(invite => invite.status === "pending").length ?? 0}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">aguardando aceite</p></div><div className="rounded-2xl border border-border/80 bg-card p-5"><p className="text-2xl font-extrabold">{invites?.filter(invite => invite.status === "accepted").length ?? 0}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">vínculos concluídos</p></div><div className="rounded-2xl border border-border/80 bg-card p-5"><p className="text-2xl font-extrabold">7 dias</p><p className="mt-1 text-xs font-semibold text-muted-foreground">validade padrão</p></div></section>

      {showForm && <form onSubmit={event => { event.preventDefault(); create.mutate({ ...form, email: form.email.trim() }); }} className="rounded-2xl border border-primary/20 bg-primary/[0.04] p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><UserPlus className="h-4 w-4" /></div><div><h2 className="font-extrabold">Gerar novo convite</h2><p className="text-xs text-muted-foreground">O link será único e ficará disponível pelo período definido.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-bold">E-mail <span className="font-normal text-muted-foreground">(opcional)</span></span><input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} placeholder="morador@email.com" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" /></label><label><span className="mb-1.5 block text-xs font-bold">Perfil de acesso</span><select value={form.role} onChange={event => setForm({ ...form, role: event.target.value as typeof form.role })} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary"><option value="resident">Morador</option><option value="staff">Funcionário</option><option value="manager">Gestor</option></select></label><label><span className="mb-1.5 block text-xs font-bold">Bloco <span className="font-normal text-muted-foreground">(opcional)</span></span><input value={form.block} onChange={event => setForm({ ...form, block: event.target.value })} placeholder="Ex.: Bloco A" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" /></label><label><span className="mb-1.5 block text-xs font-bold">Unidade <span className="font-normal text-muted-foreground">(opcional)</span></span><input value={form.unit} onChange={event => setForm({ ...form, unit: event.target.value })} placeholder="Ex.: 302" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" /></label><label><span className="mb-1.5 block text-xs font-bold">Validade</span><select value={form.expiresInDays} onChange={event => setForm({ ...form, expiresInDays: Number(event.target.value) })} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary"><option value={3}>3 dias</option><option value={7}>7 dias</option><option value={14}>14 dias</option><option value={30}>30 dias</option></select></label></div><div className="mt-5 flex justify-end"><Button type="submit" disabled={create.isPending} className="rounded-xl">{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Gerar convite</Button></div></form>}

      {created && <section className="rounded-2xl border border-[#bfe8c9] bg-[#e4f5e8] p-5 sm:p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#2b8b50] text-white"><Check className="h-5 w-5" /></div><div className="min-w-0 flex-1"><h2 className="font-extrabold text-[#236f40]">Convite pronto para enviar</h2><p className="mt-1 text-xs text-[#3d7650]">{created.email ? `O convite está preparado para ${created.email}.` : "Copie o link e envie pelo canal de sua preferência."} Válido até {formatDate(created.expiresAt)}.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><div className="flex min-w-0 flex-1 items-center rounded-xl border border-[#bfe8c9] bg-white px-3 text-xs text-muted-foreground"><Link2 className="mr-2 h-4 w-4 shrink-0 text-[#2b8b50]" /><span className="truncate">{inviteUrl}</span></div><Button type="button" onClick={copyLink} variant="outline" className="rounded-xl border-[#9bd2ab] bg-white text-[#236f40] hover:bg-white">{copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}{copied ? "Copiado" : "Copiar link"}</Button>{created.email && <a href={`mailto:${created.email}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`} className="inline-flex h-10 items-center justify-center rounded-xl bg-[#2b8b50] px-4 text-sm font-bold text-white transition hover:bg-[#236f40]"><Mail className="mr-2 h-4 w-4" />Abrir e-mail</a>}</div></div></div></section>}

      <section className="rounded-2xl border border-border/80 bg-card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Histórico</p><h2 className="mt-1 text-lg font-extrabold tracking-[-0.03em]">Convites enviados</h2></div><span className="rounded-full bg-muted px-3 py-1.5 text-xs font-bold text-muted-foreground">{invites?.length ?? 0} no total</span></div>{isLoading ? <div className="flex items-center justify-center p-8 text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Carregando convites...</div> : invites?.length ? <div className="space-y-3">{invites.map(invite => <div key={invite.id} className="flex flex-col gap-3 rounded-xl border border-border/70 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${invite.status === "accepted" ? "bg-[#e4f5e8] text-[#2b8b50]" : invite.status === "pending" ? "bg-[#fff3d9] text-[#b77a20]" : "bg-muted text-muted-foreground"}`}>{invite.status === "accepted" ? <Check className="h-4 w-4" /> : invite.status === "pending" ? <Mail className="h-4 w-4" /> : <Clipboard className="h-4 w-4" />}</div><div className="min-w-0"><p className="truncate text-sm font-bold">{invite.email || "Convite sem e-mail"}</p><p className="mt-1 text-[11px] text-muted-foreground">{roles[invite.role]}{invite.block ? ` · ${invite.block}` : ""}{invite.unit ? ` · unidade ${invite.unit}` : ""} · criado em {formatDate(invite.createdAt)}</p></div></div><div className="flex items-center gap-2 pl-12 sm:pl-0"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${invite.status === "accepted" ? "bg-[#e4f5e8] text-[#2b8b50]" : invite.status === "pending" ? "bg-[#fff3d9] text-[#a96c12]" : "bg-muted text-muted-foreground"}`}>{statuses[invite.status]}</span>{invite.status === "pending" && <button onClick={() => revoke.mutate({ id: invite.id })} className="rounded-lg px-2.5 py-1.5 text-[10px] font-bold text-destructive transition hover:bg-destructive/10">Revogar</button>}</div></div>)}</div> : <div className="rounded-xl bg-muted/60 p-8 text-center"><UserPlus className="mx-auto h-6 w-6 text-muted-foreground" /><p className="mt-3 text-sm font-bold">Nenhum convite enviado ainda</p><p className="mt-1 text-xs text-muted-foreground">Gere o primeiro convite para começar a vincular moradores.</p></div>}</section>
      <Link href="/" className="inline-flex text-xs font-bold text-primary">← Voltar para a visão geral</Link>
    </div>
  );
}
