-- CondoHub MVP — Supabase/PostgreSQL baseline
-- Execute this file once in Supabase Dashboard > SQL Editor.
-- It intentionally keeps all business data behind the server API; client-side
-- access is denied by RLS. The server will use the service-role key.

create extension if not exists pgcrypto;

create type public.app_role as enum ('user', 'admin');
create type public.condominium_status as enum ('active', 'inactive');
create type public.membership_role as enum ('resident', 'staff', 'manager', 'admin');
create type public.announcement_category as enum ('maintenance', 'finance', 'event', 'general');
create type public.ticket_category as enum ('maintenance', 'security', 'cleaning', 'billing', 'other');
create type public.ticket_status as enum ('open', 'in_progress', 'resolved');
create type public.ticket_priority as enum ('low', 'medium', 'high');
create type public.document_category as enum ('governance', 'rules', 'finance', 'meeting', 'other');
create type public.invitation_role as enum ('resident', 'staff', 'manager');
create type public.invitation_status as enum ('pending', 'accepted', 'expired', 'revoked');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  open_id text unique,
  name text,
  email text,
  login_method text default 'supabase',
  role public.app_role not null default 'user',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_signed_in timestamptz not null default timezone('utc', now())
);

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  slug varchar(120) not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.condominiums (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  name varchar(160) not null,
  address varchar(255),
  city varchar(120),
  status public.condominium_status not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.blocks (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  name varchar(80) not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (condominium_id, name)
);

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  block_id bigint references public.blocks(id) on delete set null,
  identifier varchar(40) not null,
  status public.condominium_status not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (condominium_id, block_id, identifier)
);

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  role public.membership_role not null default 'resident',
  unit varchar(40),
  block varchar(40),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, condominium_id)
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  author_id bigint not null references public.app_users(id),
  title varchar(200) not null,
  summary varchar(300) not null,
  body text not null,
  category public.announcement_category not null default 'general',
  is_pinned boolean not null default false,
  published_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  opened_by_id bigint not null references public.app_users(id),
  assigned_to_id bigint references public.app_users(id) on delete set null,
  title varchar(200) not null,
  description text not null,
  category public.ticket_category not null default 'other',
  status public.ticket_status not null default 'open',
  priority public.ticket_priority not null default 'medium',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  uploaded_by_id bigint not null references public.app_users(id),
  title varchar(200) not null,
  description varchar(300),
  category public.document_category not null default 'other',
  file_url text not null,
  file_key varchar(255) not null,
  mime_type varchar(120),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  created_by_id bigint not null references public.app_users(id),
  accepted_by_id bigint references public.app_users(id) on delete set null,
  email varchar(320) not null,
  token varchar(96) not null unique,
  role public.invitation_role not null default 'resident',
  unit varchar(40) not null,
  block varchar(40),
  status public.invitation_status not null default 'pending',
  expires_at timestamptz not null,
  accepted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists memberships_user_id_idx on public.memberships(user_id);
create index if not exists memberships_condominium_id_idx on public.memberships(condominium_id);
create index if not exists announcements_condominium_id_idx on public.announcements(condominium_id);
create index if not exists tickets_condominium_id_idx on public.tickets(condominium_id);
create index if not exists documents_condominium_id_idx on public.documents(condominium_id);
create index if not exists invitations_condominium_id_idx on public.invitations(condominium_id);
create index if not exists invitations_email_idx on public.invitations(lower(email));

-- Keep timestamps consistent with the UTC persistence rule.
drop trigger if exists app_users_set_updated_at on public.app_users;
create trigger app_users_set_updated_at before update on public.app_users for each row execute function public.set_updated_at();
drop trigger if exists organizations_set_updated_at on public.organizations;
create trigger organizations_set_updated_at before update on public.organizations for each row execute function public.set_updated_at();
drop trigger if exists condominiums_set_updated_at on public.condominiums;
create trigger condominiums_set_updated_at before update on public.condominiums for each row execute function public.set_updated_at();
drop trigger if exists blocks_set_updated_at on public.blocks;
create trigger blocks_set_updated_at before update on public.blocks for each row execute function public.set_updated_at();
drop trigger if exists units_set_updated_at on public.units;
create trigger units_set_updated_at before update on public.units for each row execute function public.set_updated_at();
drop trigger if exists memberships_set_updated_at on public.memberships;
create trigger memberships_set_updated_at before update on public.memberships for each row execute function public.set_updated_at();
drop trigger if exists announcements_set_updated_at on public.announcements;
create trigger announcements_set_updated_at before update on public.announcements for each row execute function public.set_updated_at();
drop trigger if exists tickets_set_updated_at on public.tickets;
create trigger tickets_set_updated_at before update on public.tickets for each row execute function public.set_updated_at();
drop trigger if exists documents_set_updated_at on public.documents;
create trigger documents_set_updated_at before update on public.documents for each row execute function public.set_updated_at();
drop trigger if exists invitations_set_updated_at on public.invitations;
create trigger invitations_set_updated_at before update on public.invitations for each row execute function public.set_updated_at();

-- API clients cannot access business tables directly. The server API uses the
-- Supabase service-role key, which bypasses RLS; resident access is enforced in tRPC.

alter table public.app_users enable row level security;
alter table public.organizations enable row level security;
alter table public.condominiums enable row level security;
alter table public.blocks enable row level security;
alter table public.units enable row level security;
alter table public.memberships enable row level security;
alter table public.announcements enable row level security;
alter table public.tickets enable row level security;
alter table public.documents enable row level security;
alter table public.invitations enable row level security;

-- Optional first-admin step after the first Supabase login:
-- update public.app_users set role = 'admin' where email = 'admin@example.com';
