-- Block 2: operational tickets, internal notifications and announcement lifecycle.

alter type public.ticket_status add value if not exists 'assigned';
alter type public.ticket_status add value if not exists 'waiting';
alter type public.ticket_status add value if not exists 'closed';

alter table public.tickets
  add column if not exists resolved_at timestamptz,
  add column if not exists closed_at timestamptz,
  add column if not exists reopened_at timestamptz;

alter table public.announcements
  add column if not exists archived_at timestamptz;

create table if not exists public.ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  author_id bigint not null references public.app_users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ticket_messages_ticket_created_idx
  on public.ticket_messages(ticket_id, created_at);

create table if not exists public.ticket_events (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  actor_id bigint references public.app_users(id) on delete set null,
  event_type varchar(40) not null,
  from_status public.ticket_status,
  to_status public.ticket_status,
  assigned_to_id bigint references public.app_users(id) on delete set null,
  note text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ticket_events_ticket_created_idx
  on public.ticket_events(ticket_id, created_at);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  ticket_id bigint references public.tickets(id) on delete cascade,
  kind varchar(40) not null,
  title varchar(200) not null,
  body varchar(500),
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists notifications_user_unread_idx
  on public.notifications(user_id, read_at, created_at desc);

create table if not exists public.announcement_reads (
  id bigint generated by default as identity primary key,
  announcement_id bigint not null references public.announcements(id) on delete cascade,
  user_id bigint not null references public.app_users(id) on delete cascade,
  read_at timestamptz not null default timezone('utc', now()),
  unique (announcement_id, user_id)
);

create index if not exists announcement_reads_announcement_idx
  on public.announcement_reads(announcement_id);

alter table public.ticket_messages enable row level security;
alter table public.ticket_events enable row level security;
alter table public.notifications enable row level security;
alter table public.announcement_reads enable row level security;
